Repository WildCodeSchool/2023-03-JS-TLSE-P3-Salesforce, pull requests merged in 2023-06, with the labels that each got.

#3 S03_F04_US1_home-ideas_idea-card idea_car without complete functions
  frontend/package-lock.json
  frontend/src/components/CommentButton/CommentButton.jsx
  frontend/src/components/CommentButton/CommentButton.scss
  frontend/src/components/IdeaCard/IdeaCard.jsx
  frontend/src/components/IdeaCard/IdeaCard.scss
  frontend/src/components/LikeButton/LikeButton.jsx
  frontend/src/components/LikeButton/LikeButton.scss
  frontend/src/components/SubmenuIdeaButton/SubmenuIdeaButton.jsx
  frontend/src/components/SubmenuIdeaButton/SubmenuIdeaButton.scss
  frontend/src/pages/Home.jsx
Labels: Reviewed

#6 S03 f04 us1 home ideas header
  frontend/src/components/Button/Button.jsx
  frontend/src/components/Counter.jsx
  frontend/src/components/HorizontalTabs/HorizontalTabs.jsx
  frontend/src/components/HorizontalTabs/HorizontalTabs.scss
  frontend/src/components/PageHeader/PageHeader.jsx
  frontend/src/components/PageHeader/PageHeader.scss
  frontend/src/components/SubmenuIdeaButton/SubmenuIdeaButton.scss
  frontend/src/pages/Home.jsx
  frontend/src/styles/_base.scss
  frontend/src/styles/_button.scss
  frontend/src/styles/_colors.scss
  frontend/src/styles/_shadows.scss
Labels: Reviewed, Corrections

#7 Fixes color naming and adds responsive for PageHeader
  frontend/src/components/PageHeader/PageHeader.scss
  frontend/src/styles/_colors.scss
Labels: Reviewed

#8 S03_F04_US1_home-ideas_header: Horizontal tabs and responsive + shado…
  frontend/src/components/Button/Button.jsx
  frontend/src/components/HorizontalTabs/HorizontalTabs.jsx
  frontend/src/components/HorizontalTabs/HorizontalTabs.scss
  frontend/src/components/PageHeader/PageHeader.scss
  frontend/src/pages/Home.jsx
  frontend/src/styles/_shadows.scss
Labels: Reviewed

#10 S04_F11_US2_database: Data base created and color fixes
  .DS_Store
  backend/.DS_Store
  backend/database.sql
  backend/src/.DS_Store
  frontend/src/styles/_colors.scss
Labels: Reviewed

#13 S03_F04_US1_home-ideas_header: fixing the colors import
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/styles/colors-themes/amber-color-theme.css
  frontend/src/styles/colors-themes/blue-color-theme.css
  frontend/src/styles/colors-themes/cyan-color-theme.css
  frontend/src/styles/colors-themes/emerald-color-theme.css
  frontend/src/styles/colors-themes/fuchsia-color-theme.css
  frontend/src/styles/colors-themes/green-color-theme.css
  frontend/src/styles/colors-themes/indigo-color-theme.css
  frontend/src/styles/colors-themes/lime-color-theme.css
  frontend/src/styles/colors-themes/orange-color-theme.css
  frontend/src/styles/colors-themes/pink-color-theme.css
  frontend/src/styles/colors-themes/purple-color-theme.css
  frontend/src/styles/colors-themes/red-color-theme.css
  frontend/src/styles/colors-themes/rose-color-theme.css
  frontend/src/styles/colors-themes/sky-color-theme.css
  frontend/src/styles/colors-themes/teal-color-theme.css
  frontend/src/styles/colors-themes/violet-color-theme.css
  frontend/src/styles/colors-themes/yellow-color-theme.css
  frontend/utils.jsx
Labels: Reviewed, Corrections

#14 S03 f04 us1 home ideas idea card
  frontend/src/components/Badge/Badge.jsx
  frontend/src/components/Badge/Badge.scss
  frontend/src/components/CommentButton/CommentButton.jsx
  frontend/src/components/CommentButton/CommentButton.scss
  frontend/src/components/IdeaCard/IdeaCard.jsx
  frontend/src/components/IdeaCard/IdeaCard.scss
  frontend/src/components/LikeButton/LikeButton.jsx
  frontend/src/components/LikeButton/LikeButton.scss
  frontend/src/components/SubmenuIdeaButton/SubmenuIdeaButton.jsx
  frontend/src/components/SubmenuIdeaButton/SubmenuIdeaButton.scss
  frontend/src/pages/Home.jsx
Labels: Changes requested

#15 S4 f11 us3 create exemple database cpv
  backend/.eslintrc.json
  backend/database.sql
  frontend/.eslintrc.json
Labels: Reviewed

#17 add css file for homepage
  frontend/src/App.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/Home.scss
Labels: Reviewed

#18 S03 f11 us1 navigation navbar navlink
  backend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/BoardComponentMenuBurger/BoardComponentMenuBurger.jsx
  frontend/src/components/BoardComponentMenuBurger/BoardComponentMenuBurger.scss
  frontend/src/components/BoardSubNavBar/BoardComponentNavBar.jsx
  frontend/src/components/BoardSubNavBar/BoardComponentNavBar.scss
  frontend/src/components/IdeaCard/IdeaCard.jsx
  frontend/src/components/IdeaCard/IdeaCard.scss
  frontend/src/components/IdeaMenuBurger/IdeaMenuBurger.jsx
  frontend/src/components/IdeaMenuBurger/IdeaMenuBurger.scss
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NavBar/NavBar.scss
  frontend/src/components/SubNavBarLink/SubNavBarLink.jsx
  frontend/src/components/SubNavBarLink/SubNavBarLink.scss
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/Home.scss
  frontend/src/public/assets/logo/Brand=Default.png
  frontend/src/public/assets/logo/Brand=Default.svg
  frontend/src/public/assets/logo/Logo-default.png
  frontend/src/public/assets/logo/logo_SalesForce_Theme_Clair.svg
  frontend/src/public/assets/logo/logo_SalesForce_Theme_Sombre.svg
  package-lock.json
  package.json
Labels: Reviewed

#20 S03 f04 us1 home ideas avatar
  frontend/src/App.jsx
  frontend/src/components/Avatar/Avatar.jsx
  frontend/src/components/Avatar/Avatar.scss
  frontend/src/components/Avatar/portrait.jpg
  frontend/src/components/FilterButton/FilterButton.jsx
  frontend/src/components/FilterButton/FilterButton.scss
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NavBar/NavBar.scss
  frontend/src/components/SearchBar/SearchBar.jsx
  frontend/src/components/SearchBar/SearchBar.scss
  frontend/src/components/SortButton/SortButton.jsx
  frontend/src/components/SortButton/SortButton.scss
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/Home.scss
  frontend/utils.jsx
Labels: Reviewed

#21 Adding the SearchBar and fixing images import
  frontend/src/App.jsx
  frontend/src/components/Avatar/Avatar.jsx
  frontend/src/components/Avatar/Avatar.scss
  frontend/src/components/Avatar/portrait.jpg
  frontend/src/components/FilterButton/FilterButton.jsx
  frontend/src/components/FilterButton/FilterButton.scss
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NavBar/NavBar.scss
  frontend/src/components/SearchBar/SearchBar.jsx
  frontend/src/components/SearchBar/SearchBar.scss
  frontend/src/components/SortButton/SortButton.jsx
  frontend/src/components/SortButton/SortButton.scss
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/Home.scss
  frontend/utils.jsx
Labels: Reviewed

#22 S03 f04 us1 home ideas avatar
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NavBar/NavBar.scss
Labels: Reviewed
