Repository WildCodeSchool/2023-03-JS-TLSE-P3-Salesforce, pull requests merged in 2023-07, with the labels that each got.

#25 S4 f11 us5 database models controlers cf
  .DS_Store
  backend/database.sql
  backend/src/controllers/workspaceControllers.js
  backend/src/models/WorkspaceManager.js
  backend/src/models/index.js
  backend/src/router.js
Labels: Reviewed, Corrections

#26 S4 f11 us5 database models bases
  backend/database.sql
  backend/src/controllers/commentControllers.js
  backend/src/controllers/ideaControllers.js
  backend/src/controllers/likeControllers.js
  backend/src/models/CommentManager.js
  backend/src/models/IdeaManager.js
  backend/src/models/LikeManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/src/components/SearchBar/SearchBar.scss
Labels: Reviewed, Corrections

#29 S05 f01 us1 connection
  .DS_Store
  backend/.env.sample
  backend/database.sql
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/itemControllers.js
  backend/src/controllers/userControllers.js
  backend/src/controllers/workspaceControllers.js
  backend/src/middlewares/workspaceMiddlewares.js
  backend/src/models/ItemManager.js
  backend/src/models/UserManager.js
  backend/src/models/WorkspaceManager.js
  backend/src/models/index.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Connection/Connection.jsx
  frontend/src/components/Connection/Connection.scss
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/contexts/AuthContext.jsx
  frontend/src/contexts/CompanyContext.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/styles/_checkbox.scss
  frontend/src/styles/_dropdown.scss
  frontend/src/styles/_input.scss
  frontend/src/styles/_toggle-switch.scss
  frontend/src/styles/index.scss
Labels: Reviewed

#31 S4 f11 us5 database models bases
  backend/database.sql
  backend/src/controllers/ideaControllers.js
  backend/src/controllers/ideasgroupControllers.js
  backend/src/models/IdeaManager.js
  backend/src/models/IdeasGroupManager.js
  backend/src/models/index.js
  backend/src/router.js
Labels: Reviewed

#32 S05_F01_US1_connection: Alert component created
  frontend/package-lock.json
  frontend/src/components/Alert/Alert.jsx
  frontend/src/components/Alert/Alert.scss
  frontend/src/components/Connection/Connection.jsx
  frontend/src/components/Connection/Connection.scss
Labels: Reviewed

#33 S01 f12 us1 add user
  backend/database.sql
  backend/src/models/UserManager.js
  frontend/src/App.jsx
  frontend/src/components/HorizontalTabs/HorizontalTabs.scss
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NewUserModal/NewUserModal.jsx
  frontend/src/components/NewUserModal/NewUserModal.scss
  frontend/src/pages/CompanySettings/CompanySettings.jsx
  frontend/src/pages/CompanySettings/CompanySettings.scss
  frontend/src/pages/Home/Home.jsx
  frontend/src/styles/_icon.scss
  frontend/src/styles/_input.scss
Labels: Reviewed

#34 End of sprint 5
  .DS_Store
  backend/.env.sample
  backend/database.sql
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/commentControllers.js
  backend/src/controllers/ideaControllers.js
  backend/src/controllers/ideasgroupControllers.js
  backend/src/controllers/itemControllers.js
  backend/src/controllers/likeControllers.js
  backend/src/controllers/userControllers.js
  backend/src/controllers/workspaceControllers.js
  backend/src/middlewares/workspaceMiddlewares.js
  backend/src/models/CommentManager.js
  backend/src/models/IdeaManager.js
  backend/src/models/IdeasGroupManager.js
  backend/src/models/ItemManager.js
  backend/src/models/LikeManager.js
  backend/src/models/UserManager.js
  backend/src/models/WorkspaceManager.js
  backend/src/models/index.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Alert/Alert.jsx
  frontend/src/components/Alert/Alert.scss
  frontend/src/components/Connection/Connection.jsx
  frontend/src/components/Connection/Connection.scss
  frontend/src/components/HorizontalTabs/HorizontalTabs.scss
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NewUserModal/NewUserModal.jsx
  frontend/src/components/NewUserModal/NewUserModal.scss
  frontend/src/components/SearchBar/SearchBar.scss
  frontend/src/contexts/AuthContext.jsx
  frontend/src/contexts/CompanyContext.jsx
  frontend/src/main.jsx
  frontend/src/pages/CompanySettings/CompanySettings.jsx
  frontend/src/pages/CompanySettings/CompanySettings.scss
  frontend/src/pages/Home/Home.jsx
  frontend/src/styles/_checkbox.scss
  frontend/src/styles/_dropdown.scss
  frontend/src/styles/_icon.scss
  frontend/src/styles/_input.scss
  frontend/src/styles/_toggle-switch.scss
  frontend/src/styles/index.scss
Labels: Reviewed

#35 S4 f11 us5 database models controllers team and user
  backend/src/controllers/teamControllers.js
  backend/src/controllers/userControllers.js
  backend/src/models/TeamManager.js
  backend/src/models/UserManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/src/components/Connection/Connection.jsx
Labels: Reviewed, Corrections

#36 S01 f12 us1 add user
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NewUserModal/NewUserModal.scss
  frontend/src/pages/CompanySettings/CompanySettings.jsx
  frontend/src/styles/_icon.scss
Labels: Reviewed

#37 New merges
  backend/src/controllers/teamControllers.js
  backend/src/controllers/userControllers.js
  backend/src/models/TeamManager.js
  backend/src/models/UserManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/src/components/Connection/Connection.jsx
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NewUserModal/NewUserModal.scss
  frontend/src/pages/CompanySettings/CompanySettings.jsx
  frontend/src/styles/_icon.scss
Labels: Reviewed

#39 S4 f11 us5 database models controllers team and user
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NavBar/NavBar.scss
  frontend/src/components/NewUserModal/NewUserModal.scss
Labels: Reviewed

#41 S01 f12 us1 add user
  backend/.env.sample
  backend/database.sql
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/categoryControllers.js
  backend/src/controllers/colorControllers.js
  backend/src/controllers/companyControllers.js
  backend/src/controllers/userControllers.js
  backend/src/middlewares/invitationMiddlewares.js
  backend/src/models/CategoryManager.js
  backend/src/models/ColorManager.js
  backend/src/models/CompanyManager.js
  backend/src/models/UserManager.js
  backend/src/models/index.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Alert/Alert.jsx
  frontend/src/components/Alert/Alert.scss
  frontend/src/components/Avatar/Avatar.jsx
  frontend/src/components/Avatar/Avatar.scss
  frontend/src/components/Connection/Connection.jsx
  frontend/src/components/Connection/Connection.scss
  frontend/src/components/IdeaCard/IdeaCard.jsx
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NavBar/NavBar.scss
  frontend/src/components/NewUserModal/NewUserModal.jsx
  frontend/src/pages/CompanySettings/CompanySettings.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Invitation/Invitation.jsx
  frontend/src/pages/Invitation/Invitation.scss
  frontend/src/styles/_button.scss
  frontend/src/styles/_input.scss
Labels: Reviewed, Corrections

#45 S06 f12 us1 company personalisation
  backend/src/models/CompanyManager.js
  backend/src/router.js
  frontend/src/components/ColorPicker/ColorPicker.jsx
  frontend/src/components/ColorPicker/ColorPicker.scss
  frontend/src/components/HorizontalTabs/HorizontalTabs.scss
  frontend/src/components/NavBar/NavBar.scss
  frontend/src/pages/CompanySettings/CompanySettings.jsx
  frontend/src/pages/CompanySettings/CompanySettings.scss
  frontend/src/styles/_base.scss
Labels: Reviewed

#46 S6 f10 us9 display teams company
  backend/database.sql
  backend/package-lock.json
  frontend/src/components/NewTeamModal/NewTeamModal.jsx
  frontend/src/components/NewTeamModal/NewTeamModal.scss
  frontend/src/components/TeamCard/TeamCard.jsx
  frontend/src/components/TeamCard/TeamCard.scss
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/Home.scss
Labels: Reviewed

#50 S6 f03 us9 workspace organize ideas
  frontend/src/components/IdeaCardWorkspace/IdeaCardWorkspace.jsx
  frontend/src/components/IdeaCardWorkspace/IdeaCardWorkspace.scss
  frontend/src/pages/Workspace/Workspace.jsx
  frontend/src/pages/Workspace/Workspace.scss
Labels: Reviewed

#53 S07 f12 us2 company users settings
  backend/database.sql
  backend/src/models/UserManager.js
  backend/src/router.js
  frontend/src/components/Avatar/Avatar.scss
  frontend/src/components/CompanySettingsMembers/CompanySettingsMembers.jsx
  frontend/src/components/CompanySettingsMembers/CompanySettingsMembers.scss
  frontend/src/components/DataSearchBar/DataSearchBar.jsx
  frontend/src/components/DataSearchBar/DataSearchBar.scss
  frontend/src/pages/CompanySettings/CompanySettings.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/Home.scss
  frontend/src/pages/NewPassword/NewPassword.jsx
  package-lock.json
  package.json
Labels: Reviewed

#54 S07 f04 us04 user can likes idea
  backend/src/controllers/likeControllers.js
  backend/src/models/IdeaManager.js
  backend/src/models/LikeManager.js
  backend/src/router.js
  frontend/src/components/CompanySettingsMembers/CompanySettingsMembers.scss
  frontend/src/components/IdeaCard/IdeaCard.jsx
  frontend/src/components/LikeButton/LikeButton.jsx
  frontend/src/components/TeamCard/TeamCard.jsx
Labels: Changes requested

#55 S06_F04_US1_user_can_look_his_own_ideas
  frontend/src/App.jsx
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/UserIdeas/UserIdeas.jsx
  frontend/src/pages/UserIdeas/UserIdeas.scss
Labels: Reviewed

#56 S06_F04_US4_user_can_display_own_ideas
  backend/src/controllers/ideaControllers.js
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/components/CompanySettingsMembers/CompanySettingsMembers.scss
  frontend/src/components/LikeButton/LikeButton.jsx
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/pages/UserIdeas/UserIdeas.jsx
Labels: Reviewed

#58 S06_F10_US09_user_can_display_own_teams_correction_de_la_création_équipe
  backend/src/controllers/teamControllers.js
  backend/src/models/TeamManager.js
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NewTeamModal/NewTeamModal.jsx
  frontend/src/pages/UserTeams/UserTeams.jsx
  frontend/src/pages/UserTeams/UserTeams.scss
Labels: Reviewed

#59 S05 f04 new idea
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/catHasIdeaControllers.js
  backend/src/controllers/ideaControllers.js
  backend/src/models/CatHasIdeaManager.js
  backend/src/models/IdeaManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/src/components/NewIdeaModal/NewIdeaModal.jsx
  frontend/src/components/NewIdeaModal/NewIdeaModal.scss
  frontend/src/components/SearchBar/SearchBar.jsx
  frontend/src/components/SearchBar/SearchBar.scss
  frontend/src/components/SearchCategories/SearchCategories.jsx
  frontend/src/components/SearchCategories/SearchCategories.scss
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Workspace/Workspace.jsx
  package-lock.json
Labels: Reviewed

#62 S07 f14 us03 user can display his own workspaces
  backend/src/controllers/workspaceControllers.js
  backend/src/models/WorkspaceManager.js
  backend/src/router.js
  frontend/src/components/IdeaCard/IdeaCard.scss
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/pages/UserTeams/UserTeams.jsx
  package-lock.json
  package.json
Labels: Reviewed

#63 S6 f03 us9 workspace organize ideas
  backend/src/controllers/ideaControllers.js
  backend/src/controllers/workspaceControllers.js
  backend/src/models/IdeaManager.js
  backend/src/models/WorkspaceManager.js
  backend/src/router.js
  frontend/src/components/NewDeleteUsersByWorkspaceModal/NewDeleteUsersByWorkspaceModal.jsx
  frontend/src/components/NewDeleteUsersByWorkspaceModal/NewDeleteUsersByWorkspaceModal.scss
  frontend/src/pages/Workspace/Workspace.jsx
Labels: Reviewed

#64 S6_F03_US9_workspace_organize_ideas- add the modal in order to add an…
  backend/database.sql
  backend/src/controllers/ideaControllers.js
  backend/src/controllers/teamControllers.js
  backend/src/models/IdeaManager.js
  backend/src/models/TeamManager.js
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NewIdeaModal/NewIdeaModal.jsx
  frontend/src/components/TeamCard/TeamCard.jsx
  frontend/src/pages/Team/Team.jsx
  frontend/src/pages/Workspace/Workspace.jsx
Labels: Reviewed

#65 S07 f14 us03 user can display his own workspaces
  backend/src/controllers/workspaceControllers.js
  backend/src/models/WorkspaceManager.js
  backend/src/router.js
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NewWorkspaceModal/NewWorkspaceModal.jsx
  frontend/src/components/NewWorkspaceModal/NewWorkspaceModal.scss
  frontend/src/components/SubNavBarLink/SubNavBarLink.scss
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/UserIdeas/UserIdeas.jsx
Labels: Reviewed

#66 S6_F03_US9_workspace_organize_ideas- add e pop-up validation of save …
  frontend/src/components/IdeaCardWorkspace/IdeaCardWorkspace.jsx
  frontend/src/components/IdeaCardWorkspace/IdeaCardWorkspace.scss
  frontend/src/pages/Workspace/Workspace.jsx
  frontend/src/pages/Workspace/Workspace.scss
Labels: Reviewed

#67 S08 f07 us1 user profile update
  backend/database.sql
  backend/src/models/UserManager.js
  frontend/src/App.jsx
  frontend/src/components/CompanySettingsMembers/CompanySettingsMembers.jsx
  frontend/src/components/LikeButton/LikeButton.jsx
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/NavBar/NavBar.scss
  frontend/src/components/NewDeleteUsersByWorkspaceModal/NewDeleteUsersByWorkspaceModal.jsx
  frontend/src/components/NewDeleteUsersByWorkspaceModal/NewDeleteUsersByWorkspaceModal.scss
  frontend/src/pages/CompanySettings/CompanySettings.jsx
  frontend/src/pages/Invitation/Invitation.jsx
  frontend/src/pages/UserProfile/UserProfile.jsx
  frontend/src/pages/UserProfile/UserProfile.scss
  frontend/src/pages/Workspace/Workspace.jsx
  frontend/src/pages/Workspace/Workspace.scss
Labels: Reviewed

#68 S07 f14 us03 user can display his own workspaces
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/pages/UserProfile/UserProfile.scss
Labels: Reviewed

#69 S08_F07_US1_user-profile-update: Workspace ZIndex fixed
  frontend/src/components/IdeaCardWorkspace/IdeaCardWorkspace.jsx
  frontend/src/components/IdeaCardWorkspace/IdeaCardWorkspace.scss
  frontend/src/pages/Workspace/Workspace.jsx
Labels: Reviewed

#70 Add some examples on database
  backend/database.sql
  frontend/src/components/IdeaCardWorkspace/IdeaCardWorkspace.scss
  frontend/src/components/NewTeamModal/NewTeamModal.jsx
  frontend/src/components/NewWorkspaceModal/NewWorkspaceModal.jsx
Labels: Reviewed

#71 S08_F07_US1_user-profile-update: Database updated
  backend/database.sql
  backend/src/models/WorkspaceManager.js
Labels: Reviewed

#72 S6 f03 us9 workspace organize ideas
  backend/src/controllers/catHasIdeaControllers.js
  backend/src/controllers/ideaControllers.js
  backend/src/models/CatHasIdeaManager.js
  backend/src/models/IdeaManager.js
  backend/src/router.js
  frontend/src/components/IdeaCard/IdeaCard.jsx
  frontend/src/components/IdeaCardWorkspace/IdeaCardWorkspace.jsx
  frontend/src/components/ModifiedIdeaModal/ModifiedIdeaModal.jsx
  frontend/src/components/ModifiedIdeaModal/ModifiedIdeaModal.scss
  frontend/src/components/SubmenuIdeaButton/SubmenuIdeaButton.jsx
  frontend/src/components/SubmenuIdeaButton/SubmenuIdeaButton.scss
  frontend/src/pages/Workspace/Workspace.jsx
Labels: Reviewed

#74 S05 f04 new idea new categories modal
  backend/database.sql
  backend/src/controllers/categoryControllers.js
  backend/src/models/CategoryManager.js
  backend/src/router.js
  frontend/src/components/CompanySettingCategories/CompanySettingCategories.jsx
  frontend/src/components/CompanySettingCategories/CompanySettingCategories.scss
  frontend/src/components/NewCategoryModal/NewCategoryModal.jsx
  frontend/src/components/NewCategoryModal/NewCategoryModal.scss
  frontend/src/pages/CompanySettings/CompanySettings.jsx
Labels: Reviewed

#75 company-setting-categories-add categories
  frontend/src/components/CompanySettingCategories/CompanySettingCategories.jsx
  frontend/src/components/CompanySettingCategories/CompanySettingCategories.scss
Labels: Reviewed

#76 last before presentation
  backend/database.sql
  backend/src/controllers/categoryControllers.js
  backend/src/models/CategoryManager.js
  backend/src/router.js
  frontend/src/components/CompanySettingCategories/CompanySettingCategories.jsx
  frontend/src/components/CompanySettingCategories/CompanySettingCategories.scss
  frontend/src/components/NewCategoryModal/NewCategoryModal.jsx
  frontend/src/components/NewCategoryModal/NewCategoryModal.scss
  frontend/src/pages/CompanySettings/CompanySettings.jsx
Labels: Reviewed
